### PR TITLE
Simplify the Dockerfile and the README

### PR DESCRIPTION
**Pull request by kozo2**

### CODE REVIEW

**Comment by ajshedivy** [comment]
I am experiencing some issues with getting the Cytoscape container up and running on my windows machine. I was able to build the container locally as specified by the directions, but after executing the docker run call, the container hangs on a message regarding OpenCL initialization. Have you seen this issue before, or know what may be causing the error? I am working on a project where this container may be useful. Any assistance would be greatly appreciated! 

Here is my terminal output:
```
$ docker run -p 1234:1234 -p 5900:5900 cytoscape/cytoscape-desktop
2021-09-14 17:33:46,383 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-09-14 17:33:46,384 INFO Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
2021-09-14 17:33:46,398 INFO RPC interface 'supervisor' initialized
2021-09-14 17:33:46,399 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2021-09-14 17:33:46,400 INFO supervisord started with pid 1
2021-09-14 17:33:47,406 INFO spawned: 'cytoscape' with pid 7
2021-09-14 17:33:47,414 INFO spawned: 'x11vnc' with pid 8
karaf: JAVA_HOME not set; results may vary
2021-09-14 17:33:48,503 INFO success: cytoscape entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-09-14 17:33:48,504 INFO success: x11vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
karaf.base: /cytoscape-unix-3.8.2/framework
JAVA_HOME: null
17:34:14.317 WARN  [features-3-thread-1] Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
             _
   ___ _   _| |_  ___  ___  ___  __ _ _ __   ___
  / __| | | | __|/ _ \/ __|/ __|/ _` | '_ \ / _ \
 | (__| |_| | |_| (_) \__ \ (__| (_| | |_) |  __/
  \___|\__, |\__|\___/|___/\___|\__,_| .__/ \___|
       |___/                         |_|

Cytoscape 3.8.2

Hit '<tab>' for a list of available commands
   and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or 'osgi:shutdown' to shutdown Cytoscape.

karaf@Cytoscape 3.8.2()> org.lwjgl.LWJGLException: Could not locate OpenCL library.
        at org.lwjgl.opencl.CL.create(CL.java:122)
        at org.cytoscape.opencl.cycl.CyCL.initialize(CyCL.java:69)
        at org.cytoscape.opencl.layout.CyActivator.lambda$start$0(CyActivator.java:36)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
OpenCL was not initialized because it crashed on the previous attempt.
If you think it works now, remove disable-opencl.dummy manually from Cytoscape's configuration directory.
For more information on how to troubleshoot OpenCL, please refer to http://manual.cytoscape.org/en/stable/Cytoscape_and_OpenCL_GPU.html.

```

**Comment by kozo2** [comment]
Hi @ajshedivy .
I don't think it's hung.
The message appears also in my environment, but the VNC connection and Cytoscape work fine.

image

Can you ignore that message and try Cytoscape to see if your project works?

**Comment by ajshedivy** [comment]
Was there any additional setup needed to get VNC up and running? I tried downloading the RealVNC Viewer (https://www.realvnc.com/en/connect/download/viewer/), but am unable to connect to localhost:5900 out of the box with the Cytoscape container running on the side. My connection is either rejected, or "refused" by host computer

**Comment by kozo2** [comment]
@ajshedivy Instead of the RealVNC viewer, install the UltraVNC viewer and try the same as the attached video.

https://user-images.githubusercontent.com/12192/133522202-d2be5f77-488a-436e-a981-71b69a20398e.mp4

**Pull request merged**
